/**
 * ShoppingList Model
 * Schema cho danh sách mua sắm
 */

const mongoose = require('mongoose');

const shoppingListItemSchema = new mongoose.Schema({
  foodItemId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'FoodItem',
    required: true
  },
  quantity: {
    type: Number,
    required: true,
    min: 0,
    default: 1
  },
  unitId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Unit',
    required: true
  },
  reason: {
    type: String,
    enum: ['expired', 'used_up', 'expiring_soon', 'missing_ingredient'],
    required: true
  },
  isBought: {
    type: Boolean,
    default: false
  },
  categoryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Category',
    default: null
  },
  status: {
    type: String,
    enum: ['pending', 'in_progress', 'completed', 'cancelled'],
    default: 'pending'
  },
  purchasedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  purchasedAt: {
    type: Date,
    default: null
  },
  notes: {
    type: String,
    trim: true
  },
  expiryDate: {
    type: Date,
    default: null // Optional: ngày hết hạn dự kiến khi mua
  }
}, { _id: true }); // Thêm _id: true để có thể update item bằng itemId

const shoppingListSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Tên danh sách là bắt buộc'],
    trim: true
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  familyGroupId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'FamilyGroup',
    default: null
  },
  plannedDate: {
    type: Date,
    default: Date.now
  },
  status: {
    type: String,
    enum: ['draft', 'active', 'completed', 'cancelled'],
    default: 'draft'
  },
  // Tự động tạo từ FridgeItem
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  // Nguồn tạo shopping list
  sourceMealPlanId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'MealPlan',
    default: null
  },
  items: [shoppingListItemSchema],
  completedAt: {
    type: Date,
    default: null
  }
}, {
  timestamps: true
});

// Indexes
shoppingListSchema.index({ userId: 1 });
shoppingListSchema.index({ familyGroupId: 1 });
shoppingListSchema.index({ status: 1 });
shoppingListSchema.index({ plannedDate: 1 });
shoppingListSchema.index({ userId: 1, status: 1, plannedDate: 1 });

module.exports = mongoose.model('ShoppingList', shoppingListSchema);
